server:
  port: 1102

  
eureka:
  instance:
    hostname: eureka1102.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1101.com:1101/eureka/,http://eureka1102.com:1102/eureka/,http://eureka1103.com:1103/eureka/
