spring:
  application:
    name: biz-web
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka1101.com:1101/eureka/,http://eureka1102.com:1102/eureka/,http://eureka1103.com:1103/eureka/
    register-with-eureka: false
